// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: HandySense

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Index
void ui_Index_screen_init(void);
void ui_event_Index(lv_event_t * e);
lv_obj_t * ui_Index;
lv_obj_t * ui_body;
lv_obj_t * ui_menu_box;
void ui_event_home_btn(lv_event_t * e);
lv_obj_t * ui_home_btn;
void ui_event_switch_btn(lv_event_t * e);
lv_obj_t * ui_switch_btn;
void ui_event_wifi_btn(lv_event_t * e);
lv_obj_t * ui_wifi_btn;
void ui_event_sensor_btn(lv_event_t * e);
lv_obj_t * ui_sensor_btn;
lv_obj_t * ui_main_container;
lv_obj_t * ui_home_container;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_time_now_label;
lv_obj_t * ui_wifi_status_icon;
lv_obj_t * ui_cloud_status_icon;
lv_obj_t * ui_Container22;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label51;
lv_obj_t * ui_temp_sensor_box;
lv_obj_t * ui_temp_sensor_label;
lv_obj_t * ui_temp_sensor_value;
lv_obj_t * ui_humi_sensor_box;
lv_obj_t * ui_humi_sensor_label;
lv_obj_t * ui_humi_sensor_value;
lv_obj_t * ui_soil_sensor_box;
lv_obj_t * ui_soil_sensor_label;
lv_obj_t * ui_soil_sensor_value;
lv_obj_t * ui_light_sensor_box;
lv_obj_t * ui_light_sensor_label;
lv_obj_t * ui_light_sensor_value;
lv_obj_t * ui_switch_status;
lv_obj_t * ui_Label50;
lv_obj_t * ui_o1_switch;
lv_obj_t * ui_o2_switch;
lv_obj_t * ui_o3_switch;
lv_obj_t * ui_o4_switch;
lv_obj_t * ui_switch_container;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Container10;
void ui_event_switch1_select(lv_event_t * e);
lv_obj_t * ui_switch1_select;
lv_obj_t * ui_Label10;
void ui_event_switch2_select(lv_event_t * e);
lv_obj_t * ui_switch2_select;
lv_obj_t * ui_Label2;
void ui_event_switch3_select(lv_event_t * e);
lv_obj_t * ui_switch3_select;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container2;
void ui_event_auto_select_btn(lv_event_t * e);
lv_obj_t * ui_auto_select_btn;
lv_obj_t * ui_Label4;
void ui_event_timer_select_btn(lv_event_t * e);
lv_obj_t * ui_timer_select_btn;
lv_obj_t * ui_Label5;
lv_obj_t * ui_timer_number_select_box;
void ui_event_switch1_select2(lv_event_t * e);
lv_obj_t * ui_switch1_select2;
lv_obj_t * ui_Label3;
void ui_event_switch2_select2(lv_event_t * e);
lv_obj_t * ui_switch2_select2;
lv_obj_t * ui_Label7;
void ui_event_switch3_select2(lv_event_t * e);
lv_obj_t * ui_switch3_select2;
lv_obj_t * ui_Label8;
lv_obj_t * ui_auto_body;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Container30;
lv_obj_t * ui_Container31;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Container32;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Container21;
lv_obj_t * ui_Container33;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Container34;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label39;
lv_obj_t * ui_timer_body;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Container12;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Container13;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Container14;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label21;
lv_obj_t * ui_wifi_container;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Container15;
lv_obj_t * ui_wifi_name;
lv_obj_t * ui_wifi_refresh;
lv_obj_t * ui_Label23;
void ui_event_wifi_password(lv_event_t * e);
lv_obj_t * ui_wifi_password;
lv_obj_t * ui_Container16;
lv_obj_t * ui_wifi_save;
lv_obj_t * ui_sensor_container;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Dropdown2;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Dropdown3;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Dropdown4;
lv_obj_t * ui_number_and_time_dialog;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Container18;
lv_obj_t * ui_number_digit1_input;
lv_obj_t * ui_number_digit2_input;
lv_obj_t * ui_number_split_label;
lv_obj_t * ui_number_digit3_input;
lv_obj_t * ui_number_digit4_input;
lv_obj_t * ui_Container19;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label26;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label27;
lv_obj_t * ui_loading;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_main_keyboard;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Index(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_flag_modify(ui_home_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_switch_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifi_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_sensor_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_number_and_time_dialog, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_home_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_sensor_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_wifi_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_home_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_home_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_switch_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifi_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_sensor_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_switch_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_home_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_wifi_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_sensor_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_home_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_switch_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_wifi_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_sensor_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_wifi_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_home_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_wifi_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_sensor_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_home_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_switch_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifi_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_sensor_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_sensor_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_home_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_wifi_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_sensor_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_home_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_switch_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifi_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_sensor_container, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_switch1_select(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_switch1_select, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_switch2_select, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch3_select, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_switch2_select(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_switch1_select, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch2_select, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_switch3_select, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_switch3_select(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_switch1_select, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch2_select, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch3_select, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_auto_select_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_auto_select_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_timer_select_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_auto_body, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_timer_body, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_timer_number_select_box, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_timer_select_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_auto_select_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_timer_select_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_timer_number_select_box, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_timer_body, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_auto_body, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_switch1_select2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_switch1_select2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_switch2_select2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch3_select2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_switch2_select2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_switch1_select2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch2_select2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_switch3_select2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_switch3_select2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_switch1_select2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch2_select2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch3_select2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_wifi_password(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_main_keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_main_keyboard,  ui_wifi_password);
    }
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_main_keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_number_and_time_dialog, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_number_and_time_dialog, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Index_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Index);
}
